[theme]
base = "light"
primaryColor = "#ad4670"
backgroundColor = "#fffafb"
secondaryBackgroundColor = "#fcecf2"
textColor = "#493640"
linkColor = "#a63d68"
borderColor = "#efdae3"
dataframeHeaderBackgroundColor = "#fbe8f0"
font = "sans-serif"
baseRadius = "large"
buttonRadius = "large"
headingFontSizes = ["32px", "25px", "20px", "18px", "16px", "14px"]
headingFontWeights = [600, 600, 600, 600, 600, 600]
showWidgetBorder = true
showSidebarBorder = true
chartCategoricalColors = ["#c57495", "#e6afc5", "#a687c5", "#e6b685", "#91b6a1"]

[theme.sidebar]
backgroundColor = "#f9e6ee"
secondaryBackgroundColor = "#fff7fa"
textColor = "#493640"
primaryColor = "#ad4670"
borderColor = "#efdae3"
